# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-22 21:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('D_Ninja', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ninja',
            old_name='first_name',
            new_name='f_name',
        ),
        migrations.AddField(
            model_name='ninja',
            name='l_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
